image: circleci/node:10-browsers

cache:
  key: circleci-${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

karma:
  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

code_quality:
  script:
    - npm run lint
