image: node:10

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
  artifacts:
    untracked: true
    expire_in: 8 hours

karma:
  stage: test
  script:
    - npm test

code_quality:
  stage: test
  script:
    - npm lint
